import = ["/home/chop/.config/alacritty/themes/Gotham.toml"]
live_config_reload = true

[keyboard]
bindings = [
  { key = "P", chars = "\u0002w", mods = "Command" },
  { key = "I", chars = "\u001B[105;5u", mods = "Control" },
  { key = "Space", action = "ToggleViMode", mode = "~Search", mods = "Shift|Control" },
  { key = "Y", action = "Copy", mode = "Vi|~Search" },
  { key = "Insert", action = "Paste", mods = "Shift" },
  { key = "H", action = "High", mode = "Vi|~Search", mods = "Shift" },
  { key = "M", action = "Middle", mode = "Vi|~Search", mods = "Shift" },
  { key = "L", action = "Low", mode = "Vi|~Search", mods = "Shift" },
]



[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "1", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = '[^ ]+(?:\s*)$'
command = { program = "/usr/bin/tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}", "sh", "-c", "nvim \"$0\""] }
binding = { key = "2", mods = "Control" }

[[hints.enabled]]
regex = '[^ ]+(?:\s*)$'
command = { program = "/usr/bin/tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}", "sh", "-c", "nvim \"$0\""] }
binding = { key = "H", mods = "Control|Shift" }

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
style = "Bold Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

# [[keyboard.bindings]]
# chars = "\u001Ba"
# key = "A"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bb"
# key = "B"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bc"
# key = "C"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bd"
# key = "D"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Be"
# key = "E"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bf"
# key = "F"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bg"
# key = "G"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bh"
# key = "H"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bi"
# key = "I"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bj"
# key = "J"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bk"
# key = "K"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bl"
# key = "L"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bm"
# key = "M"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bn"
# key = "N"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bo"
# key = "O"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bp"
# key = "P"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bq"
# key = "Q"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Br"
# key = "R"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bs"
# key = "S"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bt"
# key = "T"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bu"
# key = "U"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bv"
# key = "V"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bw"
# key = "W"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bx"
# key = "X"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001By"
# key = "Y"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001Bz"
# key = "Z"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001BA"
# key = "A"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BB"
# key = "B"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BC"
# key = "C"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BD"
# key = "D"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BE"
# key = "E"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BF"
# key = "F"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BG"
# key = "G"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BH"
# key = "H"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BI"
# key = "I"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BJ"
# key = "J"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BK"
# key = "K"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BL"
# key = "L"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BM"
# key = "M"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BN"
# key = "N"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BO"
# key = "O"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BP"
# key = "P"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BQ"
# key = "Q"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BR"
# key = "R"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BS"
# key = "S"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BT"
# key = "T"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BU"
# key = "U"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BV"
# key = "V"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BW"
# key = "W"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BX"
# key = "X"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BY"
# key = "Y"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001BZ"
# key = "Z"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B1"
# key = "Key1"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B2"
# key = "Key2"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B3"
# key = "Key3"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B4"
# key = "Key4"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B5"
# key = "Key5"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B6"
# key = "Key6"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B7"
# key = "Key7"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B8"
# key = "Key8"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B9"
# key = "Key9"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B0"
# key = "Key0"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u0000"
# key = "Space"
# mods = "Control"
#
# [[keyboard.bindings]]
# chars = "\u001B`"
# key = "Grave"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B~"
# key = "Grave"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B."
# key = "Period"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B*"
# key = "Key8"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B#"
# key = "Key3"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B>"
# key = "Period"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B<"
# key = "Comma"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B_"
# key = "Minus"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B%"
# key = "Key5"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B^"
# key = "Key6"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# chars = "\u001B\\"
# key = "Backslash"
# mods = "Alt"
#
# [[keyboard.bindings]]
# chars = "\u001B|"
# key = "Backslash"
# mods = "Alt|Shift"
#
# [[keyboard.bindings]]
# action = "ToggleSimpleFullscreen"
# key = "Return"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "IncreaseFontSize"
# key = "Plus"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "DecreaseFontSize"
# key = "Minus"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "ResetFontSize"
# key = "Key0"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "Hide"
# key = "H"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "Quit"
# key = "Q"
# mods = "Command"

# [mouse]
# hide_when_typing = true
#
# [mouse.double_click]
# threshold = 300
#
# [mouse.hints]
# modifiers = "Command"
#
# [mouse.hints.launcher]
# program = "open"
#
# [mouse.triple_click]
# threshold = 300

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 3

[window]
blur = true
# PROJECT: alacritty_transparency
opacity = 1.0
decorations = "Full" # "Full" | "None"
startup_mode = "Maximized"
[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 5
y = 5
